version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "🚀 merge it!"
    ignore:
      - dependency-name: eslint
        versions: ["9.x"]
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
