version: "3.7"

services:
  db-dev:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nots
    ports:
      - "9876:5432"
    volumes:
      - app-volume:/var/lib/postgresql/data

  db-test:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nots
    ports:
      - "9877:5432"

volumes:
  app-volume: #
