name: 🚀 Deploy
on:
  push:
    branches:
      - main

env:
  CI: 'true'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Lint code
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Transpile TypeScript
        run: npm run typecheck

  deploy-app-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - unit-tests
      - lint
      - typecheck
    environment:
      name: app-staging
      url: https://nots-app-staging.vercel.app/
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Build app
        run: npx vercel build --yes --local-config vercel-app.json --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --local-config vercel-app.json --yes --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-app-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - deploy-app-staging
    environment:
      name: app-prod
      url: https://nots-app-prod.vercel.app/
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Build app
        run: npx vercel build --yes --local-config vercel-app.json --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: npx vercel deploy --yes --local-config vercel-app.json --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  
  deploy-ui-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - deploy-app-staging
    environment:
      name: ui-prod
      url: https://nots-ui-prod.vercel.app/
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Build UI
        run: npx vercel build --prod --yes --local-config vercel-ui.json --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --yes --prod --local-config vercel-ui.json --token=${{ secrets.VERCEL_TOKEN }}
