name: 👀 Check changes
on: pull_request

env:
  CI: 'true'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Lint code
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Transpile TypeScript
        run: npm run typecheck

  preview-app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: app-preview
      url: ${{ steps.get-url.outputs.PREVIEW_URL }}
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Deploy to Vercel
        run: npx vercel deploy --local-config vercel-app.json --yes --token ${{ secrets.VERCEL_TOKEN }}  > deployment-url.txt
      - name: Get URL
        id: get-url
        run: echo "PREVIEW_URL=$(cat deployment-url.txt)" >> "$GITHUB_OUTPUT"
  
  preview-ui:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: ui-preview
      url: ${{ steps.get-url.outputs.PREVIEW_URL }}
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Deploy to Vercel
        run: npx vercel deploy --yes --local-config vercel-ui.json --token ${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
      - name: Get URL
        id: get-url
        run: echo "PREVIEW_URL=$(cat deployment-url.txt)" >> "$GITHUB_OUTPUT"
